version: "3.8"

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - "9090:80"
    volumes:
      - ./backend:/var/www/html/backend # Mount backend directory to /var/www/html/backend
      - ./frontend:/var/www/html # Mount frontend directory directly to /var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: foodventeny_db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: foodventeny_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
